[package]
name = "kvs"
version = "0.1.0"
edition = "2024"
authors = ["Samuel Vanderwaal <samuel.vanderwaal@email.com>"]
description = "A simple key-value store"

[features]
bincode = []

[lib]
test = false
doctest = true

[[bin]]
name = "kvs-client"
path = "src/bin/kvs_client.rs"

[[bin]]
name = "kvs-server"
path = "src/bin/kvs_server.rs"

[dependencies]
bincode = {version = "2.0.1", features = ["serde"]}
bson = { version = "3.0.0", features = ["serde"] }
clap = { version = "4.5.47", features = ["derive"] }
serde = "1.0.225"
thiserror = "2.0.16"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }

[dev-dependencies]
assert_cmd = "0.11"
criterion = "0.3"
predicates = "1.0.0"
rand = "0.6.5"
tempfile = "3.0.7"
walkdir = "2.2.7"

[[bench]]
name = "set_operations"
harness = false

[[bench]]
name = "get_operations"
harness = false

[[bench]]
name = "remove_operations"
harness = false
